### PR TITLE
Fixed class loader leaks

### LINKED ISSUE #726: Memory leaks on Application servers
I have discovered a major memory leak caused by Tyrus,
it hangs on user's classes after the user application has been unloaded.
It took me a while to figure it out, but I have a small PR that fixes it

### PR DESCRIPTION
**Pull request by lprimak**
Fixes #726 

No longer hangs on to context class loaders and user application classes when app is undeployed
Tracked this down over multiple passes with VisualVM heap dumps to find out GC roots.

- refactored anonymous inner class into `TyrusServerContainerImpl` so the former doesn't hand on to the `ServletContext` and thus application's class loader
- reset `engine` and `serverContainer` to null after `TyrusServletFilter` is destroyed, so they do not hang on to user application classes when application is unloded.

### CODE REVIEW

File: containers/servlet/src/main/java/org/glassfish/tyrus/servlet/TyrusServletContainerInitializer.java [hunk 1]
```diff
@@ -83,34 +83,9 @@ public void onStartup(Set<Class<?>> classes, final ServletContext ctx) throws Se
...
-            public void register(ServerEndpointConfig serverEndpointConfig) throws DeploymentException {
-                engine.register(serverEndpointConfig, ctx.getContextPath());
-            }
-
-            @Override
-            public WebSocketEngine getWebSocketEngine() {
-                return engine;
-            }
-        };
+        final TyrusServerContainer serverContainer = new TyrusServerContainerImpl(classes, applicationEventListener,
```
Comment (lprimak) [inline containers/servlet/src/main/java/org/glassfish/tyrus/servlet/TyrusServletContainerInitializer.java:86]: Converted anonymous inner class to static member class, so context isn't implicitly brought in and leaked

File: containers/servlet/src/main/java/org/glassfish/tyrus/servlet/TyrusServletContainerInitializer.java [hunk 2]
```diff
@@ -224,4 +199,55 @@ private ApplicationEventListener createApplicationEventListener(final ServletCon
         }
         return null;
     }
+
+    private static class TyrusServerContainerImpl extends TyrusServerContainer {
```
Comment (lprimak) [inline containers/servlet/src/main/java/org/glassfish/tyrus/servlet/TyrusServletContainerInitializer.java:203]: The aforementioned refactoring

File: containers/servlet/src/main/java/org/glassfish/tyrus/servlet/TyrusServletFilter.java [hunk 3]
```diff
@@ -303,5 +303,7 @@ private synchronized JAXBContext getWsadlJaxbContext() throws JAXBException {
     public void destroy() {
         serverContainer.stop();
         engine.getApplicationEventListener().onApplicationDestroyed();
+        serverContainer = null;
```
Comment (lprimak) [inline containers/servlet/src/main/java/org/glassfish/tyrus/servlet/TyrusServletFilter.java:306]: Both of these hang on to application classes, so they have to be reset to null

**Comment by lprimak** [comment]
@jansupol This is a pretty bad bug. Hopefully this will be merged soon.
thank you!

**Comment by lprimak** [comment]
@jansupol Looks like with Travis CI migration to .com the tests are stuck indefinitely:
See https://travis-ci.community/t/builds-stuck-in-received-state/10342/6?u=lprimak

**Comment by lprimak** [comment]
Test failures are completely unrelated. I will try to push an empty commit to trigger the job again

**Comment by lprimak** [comment]
Anything we can do to get these PRs merged?
Thank you

**Comment by lprimak** [comment]
@jansupol Anything I can do to get this PR merged? Thank you!

**Comment by lprimak** [comment]
@jansupol Another month goes by :)

**Comment by lprimak** [comment]
@m0mus Any chance for someone to look at this?

**Review by arjantijms — APPROVED** [review]

**Comment by arjantijms** [comment]
Though I'm not that experienced with this particular section of code, it looks okay. Accepting by lazy consensus.

**Comment by lprimak** [comment]
yay thanks Arjan!
